name: Pull request checker

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  Pull_request_checker:
    runs-on: ubuntu-latest
    name: The xml_checker tests all changed-files from the pull-request

    steps:
      - uses: GetDutchie/github-action-delete-comment@v1.0.0
        with: 
          github_token: ${{ secrets.DUTCHIE_BOT_TOKEN }}
          delete_user_name: github-actions[bot]

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install bs4 lxml

      - name: Get the version of the commits
        id: get_version
        uses: hsblhsn/version-or-commit-sha@main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Verification of the files with the python script
        id: first-lines
        run: |
          bad_file=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.xml ]]; then
              echo "Processing $file"
              result=$(python .github/workflows/xml_check.py "$file")
              if [[ -n $result && $result != 'None' ]]; then
                bad_file="${bad_file}<br>Le fichier $file n'a pas les balises :\`${result}\`<br>"
                echo "BAD_FILES=$bad_file" >> $GITHUB_ENV
              fi
            else
              echo "Skipping $file - not an XML file"
            fi
          done

      - name: Retrieve Pull Request
        id: pr
        run: |
          echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

      - name: Create an Error comment
        if: ${{ env.BAD_FILES != '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            We have a problem! :wave:

      - name: Create Issue on Error
        if: ${{ env.BAD_FILES != '' }}
        uses: lionelrrivas/github-issue-creator@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Missing XML Tags
          body: |
            ${{ env.BAD_FILES }}
            Push version: ${{ steps.get_version.outputs.VERSION_OR_COMMIT_SHA }}
            Look at this PR : ${{ github.repository }}/issues/${{ steps.pr.outputs.pr_number }}
          assignees: |
            ${{ github.repository_owner }}
            ${{ github.actor }}
