name: Pull request checker

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  Pull_request_checker:  
    runs-on: ubuntu-latest
    name: The xml_checker test all changed-files from the pull-request
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: |
            yo je suis là
