name: Pull request checker

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  Pull_request_checker:
    runs-on: ubuntu-latest

    steps:
    
      - name: Retrieve Pull Request
        id: pr
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          
      - name: Deleting old comments from the bot 
        uses: GetDutchie/github-action-delete-comment@v1.0.0
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ env.pr_number }} 

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install bs4 lxml

      - name: Get the version of the commits
        id: get_version
        uses: hsblhsn/version-or-commit-sha@main

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Verification of the files with the python script
        id: first-lines
        run: |
          bad_file=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.xml ]]; then
              echo "Processing $file"
              result=$(python .github/workflows/xml_check.py "$file")
              echo "$result"
                if [[ -n $result && $result != 'None' ]]; then
                  bad_file="<br>${result}<br>"
                  echo "BAD_FILES=$bad_file" >> $GITHUB_ENV
                fi
            else
              echo "Skipping $file - not an XML file"
            fi
          done
      
      - name: Create a Succes comment
        if: ${{ env.BAD_FILES == '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Good Job your files are well encoded, you can merge your pull request ! :fire::fire::fire::fire::fire:
      
      - name: Create an Error comment
        if: ${{ env.BAD_FILES != '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
         filePath: .github/workflows/error_comment.md
         
      - name: Create Issue on Error
        if: ${{ env.BAD_FILES != '' }}
        uses: lionelrrivas/github-issue-creator@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Missing XML Tags
          body: |
            ${{ env.BAD_FILES }}
            Push version: ${{ steps.get_version.outputs.VERSION_OR_COMMIT_SHA }}
            Look at this PR : ${{ github.repository }}/issues/${{ env.pr_number }}
          assignees: |
            ${{ github.repository_owner }}
            ${{ github.actor }}
            
      - name: Exit with an error
        if: ${{ env.BAD_FILES != '' }}
        run: exit 1
