name: CI

on:
  push:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Access token example
        run: |
            echo ${{ secrets.ACTION }}
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install lxml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Set up environment file
        run: echo "MISSING_TAGS=" >> $GITHUB_ENV

      - name: Run Python script on changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file"
            output=$(python .github/workflows/xml_check.py "$file")
            exit_code=$?
            if [ $exit_code -eq 59 ]; then
              echo "The file $file is missing these tags: $output" >> missing_tags.txt
              echo "::set-env name=MISSING_TAGS::1"
            fi
          done

      - name: Create Issue on Error
        if: env.MISSING_TAGS == '1'
        uses: peter-evans/create-issue@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Missing XML Tags
          body: |
            The following files have missing tags:
            $(cat missing_tags.txt)
          assignees: ${{ github.repository_owner }}
