name: CI

on:
  push:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Access token example
        run: |
            echo ${{ secrets.ACTION }}
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install lxml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Apply Python script to changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file"
            python .github/workflows/xml_check.py "$file"
            exit_code=$?
            if [ $exit_code -eq 59 ]; then
              exit 1
            fi
          done

      - name: Create Issue on Error
        if: ${{ failure() }}
        uses: bryannice/gitactions-git-issue-creation@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          GITHUB_REPO_OWNER: 'bryan-nice'
          GITHUB_REPO_NAME: 'github-issue-creation'
          GITHUB_ISSUE_TITLE: 'Demo''ing Git Issue Creation'
          GITHUB_ISSUE_BODY: 'Demo''ing Git Issue Creation'
