name: CI

on:
  push:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Access token example
        run: |
            echo ${{ secrets.ACTION }}
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install lxml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Set up environment file
        run: echo "MISSING_TAGS=" >> $GITHUB_ENV

      - name: Run Python script on changed files
        id: missing-tags
        run: |
          missing_tags=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file"
            output=$(python .github/workflows/xml_check.py "$file")
            exit_code=$?
            if [ $exit_code -ne 0 ]; then
              missing_tags+="The file $file is missing these tags: $output\n"
            fi
          done
          echo "::set-output name=missing_tags::$missing_tags"

      - name: Create Issue on Error
        if: ${{ failure() }}
        uses: lionelrrivas/github-issue-creator@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Missing XML Tags
          body: ${{ steps.missing-tags.outputs.missing_tags }}
          assignees: |
            ${{ github.repository_owner }}
            ${{ github.actor }}
