name: XML Check

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  xml-check:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get last commit hashes
        run: |
          LAST_COMMIT=$(git log -1 --format=%H)
          PREVIOUS_COMMIT=$(git log -2 --format=%H | tail -1)
          echo "LAST_COMMIT=$LAST_COMMIT" >> $GITHUB_ENV
          echo "PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $GITHUB_ENV

      - name: Get changed files
        id: git-diff
        run: |
          echo "changed_files=$(git diff --name-only $PREVIOUS_COMMIT $LAST_COMMIT)" >> $GITHUB_ENV

      - name: Print changed files
        run: |
          echo "Changed files: $changed_files"
