name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: ${{ github.actor }}
          FIRST_NAME: ${{ github.event_name }}
          MIDDLE_NAME: "he :"
          LAST_NAME: "made a :"
        run: |
          echo $MIDDLE_NAME $MY_VAR   $LAST_NAME $FIRST_NAME
