name: CI

on:
  push:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Modules
        run: |
          python -m pip install lxml

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37

      - name: Set FIRST_LINES variable
        id: first-lines
        run: |
          first_line=""  # Initialize the variable
          for file in  ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Processing $file"
            result=$(python .github/workflows/xml_check.py "$file")  # Run the script and capture the output
            first_line="'${first_line}' '${result}'"
            echo "FIRST_LINES=$first_line" >> $GITHUB_ENV
          done


      - name: Create Issue on Error
        uses: lionelrrivas/github-issue-creator@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Missing XML Tags
          body: |
            ${{ env.FIRST_LINES }}
          assignees: |
            ${{ github.repository_owner }}
            ${{ github.actor }}
