name: Workflow Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output Value
        id: set_output
        run: echo "name=Hello, World!" >> $GITHUB_STATE
        
      - name: Use Output Value
        run: echo "The output value is ${{ env.name }}"
